import type { AppState, Branch, Product } from "./types";

export const branches: Branch[] = ["บ้านโจ้", "ท่ารั้ว", "เกษตรใหม่"];

export const productTypeLabel: Record<Product["type"], string> = {
  raw_material: "วัตถุดิบ",
  packaging: "บรรจุภัณฑ์",
  purchased_finished_good: "ซื้อมาขาย",
  produced_finished_good: "ผลิตเอง",
};

export const products: Product[] = [
  { id: "PTG-001", name: "ข้าวกะเพราไก่", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 55, standardCost: 32, costStartDate: "2026-06-01", supplier: "The Grand's", active: false },
  { id: "PTG-002", name: "ข้าวกะเพราไก่", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 59, standardCost: 35, costStartDate: "2026-06-15", supplier: "The Grand's", active: true },
  { id: "PTG-003", name: "ข้าวผัดหมู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 55, standardCost: 31, costStartDate: "2026-06-01", supplier: "The Grand's", active: false },
  { id: "PTG-004", name: "ข้าวผัดหมู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 59, standardCost: 34, costStartDate: "2026-06-15", supplier: "The Grand's", active: true },
  { id: "PTG-005", name: "ข้าวไก่กระเทียม", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 55, standardCost: 33, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-006", name: "ข้าวหมูทอด", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 60, standardCost: 36, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-007", name: "ข้าวลาบหมู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 59, standardCost: 34, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-008", name: "ข้าวน้ำพริกปลาทู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 65, standardCost: 40, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-009", name: "ข้าวแกงเขียวหวานไก่", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 62, standardCost: 38, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-010", name: "ข้าวพะแนงหมู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 62, standardCost: 39, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-011", name: "น้ำดื่ม 600 มล.", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 10, standardCost: 6, costStartDate: "2026-06-01", supplier: "The Grand's", active: false },
  { id: "PTG-012", name: "น้ำดื่ม 600 มล.", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 12, standardCost: 7, costStartDate: "2026-06-20", supplier: "The Grand's", active: true },
  { id: "PTG-013", name: "ชาไทยขวด", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 25, standardCost: 15, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-014", name: "กาแฟเย็นขวด", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 30, standardCost: 18, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-015", name: "น้ำเก๊กฮวย", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 20, standardCost: 11, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-016", name: "น้ำลำไย", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 22, standardCost: 13, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-017", name: "น้ำอัญชันมะนาว", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 25, standardCost: 14, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-018", name: "น้ำกระเจี๊ยบ", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 22, standardCost: 12, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-019", name: "เค้กกล้วยหอม", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 35, standardCost: 20, costStartDate: "2026-06-01", supplier: "The Grand's", active: false },
  { id: "PTG-020", name: "เค้กกล้วยหอม", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 39, standardCost: 23, costStartDate: "2026-06-18", supplier: "The Grand's", active: true },
  { id: "PTG-021", name: "บราวนี่", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 45, standardCost: 26, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-022", name: "คุกกี้เนย", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 30, standardCost: 17, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-023", name: "ขนมถ้วย", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 35, standardCost: 19, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-024", name: "พายไก่", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 42, standardCost: 24, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-025", name: "ข้าวต้มมัด", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 25, standardCost: 14, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-026", name: "วุ้นกะทิ", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 25, standardCost: 13, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-027", name: "แซนด์วิชทูน่า", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 45, standardCost: 28, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-028", name: "แซนด์วิชแฮมชีส", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 49, standardCost: 31, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-029", name: "โรตีกรอบ", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 29, standardCost: 16, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-030", name: "ขนมปังกระเทียม", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 35, standardCost: 20, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PGH-001", name: "ข้าวกะเพราไก่", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 59, standardCost: 29, costStartDate: "2026-06-01", supplier: "Grand House", active: false },
  { id: "PGH-002", name: "ข้าวกะเพราไก่", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 65, standardCost: 33, costStartDate: "2026-06-16", supplier: "Grand House", active: true },
  { id: "PGH-003", name: "ข้าวผัดหมู", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 59, standardCost: 30, costStartDate: "2026-06-01", supplier: "Grand House", active: false },
  { id: "PGH-004", name: "ข้าวผัดหมู", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 65, standardCost: 34, costStartDate: "2026-06-16", supplier: "Grand House", active: true },
  { id: "PGH-005", name: "ข้าวไก่กระเทียม", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 60, standardCost: 31, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-006", name: "ข้าวหมูทอดน้ำปลา", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 69, standardCost: 38, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-007", name: "ข้าวไข่ข้นกุ้ง", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 79, standardCost: 45, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-008", name: "ข้าวคั่วกลิ้งหมู", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 69, standardCost: 39, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-009", name: "ข้าวผัดกุนเชียง", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 65, standardCost: 36, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-010", name: "ข้าวหมูผัดพริกแกง", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 65, standardCost: 35, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-011", name: "น้ำดื่ม 600 มล.", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 10, standardCost: 5, costStartDate: "2026-06-01", supplier: "Grand House", active: false },
  { id: "PGH-012", name: "น้ำดื่ม 600 มล.", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 12, standardCost: 6, costStartDate: "2026-06-20", supplier: "Grand House", active: true },
  { id: "PGH-013", name: "ชาไทย Grand House", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 35, standardCost: 17, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-014", name: "กาแฟดำเย็น", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 35, standardCost: 15, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-015", name: "ลาเต้เย็น", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 45, standardCost: 22, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-016", name: "โกโก้เย็น", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 45, standardCost: 23, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-017", name: "น้ำผึ้งมะนาว", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 40, standardCost: 19, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-018", name: "ชามะนาว", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 35, standardCost: 16, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-019", name: "เค้กกล้วยหอม", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 39, standardCost: 18, costStartDate: "2026-06-01", supplier: "Grand House", active: false },
  { id: "PGH-020", name: "เค้กกล้วยหอม", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 45, standardCost: 22, costStartDate: "2026-06-18", supplier: "Grand House", active: true },
  { id: "PGH-021", name: "บราวนี่หน้าแน่น", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 49, standardCost: 25, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-022", name: "คุกกี้ช็อกโกแลต", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 35, standardCost: 16, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-023", name: "แพนเค้กน้ำผึ้ง", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 59, standardCost: 29, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-024", name: "วาฟเฟิล", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 55, standardCost: 27, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-025", name: "ขนมปังปิ้งเนยนม", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 35, standardCost: 14, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-026", name: "ขนมปังปิ้งสังขยา", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 39, standardCost: 16, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-027", name: "ครัวซองต์เนยสด", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 69, standardCost: 38, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-028", name: "ทาร์ตไข่", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 45, standardCost: 24, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-029", name: "มัฟฟินบลูเบอร์รี", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 49, standardCost: 26, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-030", name: "โดนัทน้ำตาล", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 35, standardCost: 18, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-001", name: "เนื้อไก่สด", type: "raw_material", category: "เนื้อสัตว์", unit: "กก.", salePrice: 0, standardCost: 65, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-002", name: "เนื้อหมูสด", type: "raw_material", category: "เนื้อสัตว์", unit: "กก.", salePrice: 0, standardCost: 85, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-003", name: "กุ้งแชบ๊วย", type: "raw_material", category: "เนื้อสัตว์", unit: "กก.", salePrice: 0, standardCost: 220, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-004", name: "ข้าวหอมมะลิ", type: "raw_material", category: "ของแห้ง", unit: "กก.", salePrice: 0, standardCost: 35, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-005", name: "น้ำมันพืช", type: "raw_material", category: "เครื่องปรุง", unit: "ลิตร", salePrice: 0, standardCost: 45, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-006", name: "ซีอิ๊วขาว", type: "raw_material", category: "เครื่องปรุง", unit: "ลิตร", salePrice: 0, standardCost: 55, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-007", name: "น้ำตาลทราย", type: "raw_material", category: "เครื่องปรุง", unit: "กก.", salePrice: 0, standardCost: 28, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-008", name: "ไข่ไก่เบอร์ 2", type: "raw_material", category: "อื่นๆ", unit: "ฟอง", salePrice: 0, standardCost: 4.5, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-009", name: "ใบกะเพรา", type: "raw_material", category: "ผัก", unit: "กก.", salePrice: 0, standardCost: 80, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-010", name: "พริกขี้หนู", type: "raw_material", category: "ผัก", unit: "กก.", salePrice: 0, standardCost: 60, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-011", name: "กระเทียม", type: "raw_material", category: "เครื่องปรุง", unit: "กก.", salePrice: 0, standardCost: 45, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-012", name: "แป้งสาลี", type: "raw_material", category: "ของแห้ง", unit: "กก.", salePrice: 0, standardCost: 32, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-013", name: "เนยสด", type: "raw_material", category: "อื่นๆ", unit: "กก.", salePrice: 0, standardCost: 180, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-014", name: "นมสด", type: "raw_material", category: "อื่นๆ", unit: "ลิตร", salePrice: 0, standardCost: 55, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-015", name: "ผงโกโก้", type: "raw_material", category: "เครื่องปรุง", unit: "กก.", salePrice: 0, standardCost: 250, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-016", name: "น้ำเปล่า (สำหรับผลิต)", type: "raw_material", category: "น้ำ", unit: "ลิตร", salePrice: 0, standardCost: 5, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-017", name: "น้ำแข็ง", type: "raw_material", category: "น้ำ", unit: "กก.", salePrice: 0, standardCost: 8, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-001", name: "กล่องข้าวกล่อง 600 มล.", type: "packaging", category: "บรรจุภัณฑ์", unit: "ใบ", salePrice: 0, standardCost: 4, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-002", name: "ถุงพลาสติกใส", type: "packaging", category: "บรรจุภัณฑ์", unit: "ใบ", salePrice: 0, standardCost: 1.5, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-003", name: "ช้อนไม้", type: "packaging", category: "บรรจุภัณฑ์", unit: "คัน", salePrice: 0, standardCost: 0.8, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-004", name: "ส้อมไม้", type: "packaging", category: "บรรจุภัณฑ์", unit: "คัน", salePrice: 0, standardCost: 0.8, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-005", name: "ฝาแก้ว 95 มม.", type: "packaging", category: "บรรจุภัณฑ์", unit: "อัน", salePrice: 0, standardCost: 2, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-006", name: "หลอดกระดาษ", type: "packaging", category: "บรรจุภัณฑ์", unit: "อัน", salePrice: 0, standardCost: 1.2, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-007", name: "กล่องเบเกอรี่เล็ก", type: "packaging", category: "บรรจุภัณฑ์", unit: "ใบ", salePrice: 0, standardCost: 3.5, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-008", name: "ถุงกระดาษมีหู", type: "packaging", category: "บรรจุภัณฑ์", unit: "ใบ", salePrice: 0, standardCost: 3, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
];

export const initialState: AppState = {
  products,
  lots: [],
  recipes: [],
  batches: [],
  sessions: [],
  sales: [],
  saleItems: [],
  payments: [],
  movements: [],
  documents: [],
  cashEntries: [],
  adjustments: [],
  closeShifts: [],
  auditLogs: [],
  taxSettings: {
    vatEnabled: false,
    vatRate: 7,
    priceIncludesVat: true,
  },
};
