import type { AppState, Branch, Product } from "./types";

export const branches: Branch[] = ["บ้านโจ้", "ท่ารั้ว", "เกษตรใหม่"];

export const productTypeLabel: Record<Product["type"], string> = {
  raw_material: "วัตถุดิบ",
  packaging: "บรรจุภัณฑ์",
  purchased_finished_good: "ซื้อมาขาย",
  produced_finished_good: "ผลิตเอง",
};

export const products: Product[] = [
  { id: "PTG-001", name: "ข้าวกะเพราไก่", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 55, standardCost: 32, costStartDate: "2026-06-01", supplier: "The Grand's", active: false },
  { id: "PTG-002", name: "ข้าวกะเพราไก่", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 59, standardCost: 35, costStartDate: "2026-06-15", supplier: "The Grand's", active: true },
  { id: "PTG-003", name: "ข้าวผัดหมู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 55, standardCost: 31, costStartDate: "2026-06-01", supplier: "The Grand's", active: false },
  { id: "PTG-004", name: "ข้าวผัดหมู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 59, standardCost: 34, costStartDate: "2026-06-15", supplier: "The Grand's", active: true },
  { id: "PTG-005", name: "ข้าวไก่กระเทียม", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 55, standardCost: 33, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-006", name: "ข้าวหมูทอด", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 60, standardCost: 36, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-007", name: "ข้าวลาบหมู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 59, standardCost: 34, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-008", name: "ข้าวน้ำพริกปลาทู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 65, standardCost: 40, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-009", name: "ข้าวแกงเขียวหวานไก่", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 62, standardCost: 38, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-010", name: "ข้าวพะแนงหมู", type: "purchased_finished_good", category: "ข้าวกล่อง", unit: "ชิ้น", salePrice: 62, standardCost: 39, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-011", name: "น้ำดื่ม 600 มล.", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 10, standardCost: 6, costStartDate: "2026-06-01", supplier: "The Grand's", active: false },
  { id: "PTG-012", name: "น้ำดื่ม 600 มล.", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 12, standardCost: 7, costStartDate: "2026-06-20", supplier: "The Grand's", active: true },
  { id: "PTG-013", name: "ชาไทยขวด", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 25, standardCost: 15, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-014", name: "กาแฟเย็นขวด", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 30, standardCost: 18, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-015", name: "น้ำเก๊กฮวย", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 20, standardCost: 11, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-016", name: "น้ำลำไย", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 22, standardCost: 13, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-017", name: "น้ำอัญชันมะนาว", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 25, standardCost: 14, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-018", name: "น้ำกระเจี๊ยบ", type: "purchased_finished_good", category: "น้ำ", unit: "ชิ้น", salePrice: 22, standardCost: 12, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-019", name: "เค้กกล้วยหอม", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 35, standardCost: 20, costStartDate: "2026-06-01", supplier: "The Grand's", active: false },
  { id: "PTG-020", name: "เค้กกล้วยหอม", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 39, standardCost: 23, costStartDate: "2026-06-18", supplier: "The Grand's", active: true },
  { id: "PTG-021", name: "บราวนี่", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 45, standardCost: 26, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-022", name: "คุกกี้เนย", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 30, standardCost: 17, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-023", name: "ขนมถ้วย", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 35, standardCost: 19, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-024", name: "พายไก่", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 42, standardCost: 24, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-025", name: "ข้าวต้มมัด", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 25, standardCost: 14, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-026", name: "วุ้นกะทิ", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 25, standardCost: 13, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-027", name: "แซนด์วิชทูน่า", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 45, standardCost: 28, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-028", name: "แซนด์วิชแฮมชีส", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 49, standardCost: 31, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-029", name: "โรตีกรอบ", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 29, standardCost: 16, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PTG-030", name: "ขนมปังกระเทียม", type: "purchased_finished_good", category: "ขนม", unit: "ชิ้น", salePrice: 35, standardCost: 20, costStartDate: "2026-06-01", supplier: "The Grand's", active: true },
  { id: "PGH-001", name: "ข้าวกะเพราไก่", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 59, standardCost: 29, costStartDate: "2026-06-01", supplier: "Grand House", active: false },
  { id: "PGH-002", name: "ข้าวกะเพราไก่", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 65, standardCost: 33, costStartDate: "2026-06-16", supplier: "Grand House", active: true },
  { id: "PGH-003", name: "ข้าวผัดหมู", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 59, standardCost: 30, costStartDate: "2026-06-01", supplier: "Grand House", active: false },
  { id: "PGH-004", name: "ข้าวผัดหมู", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 65, standardCost: 34, costStartDate: "2026-06-16", supplier: "Grand House", active: true },
  { id: "PGH-005", name: "ข้าวไก่กระเทียม", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 60, standardCost: 31, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-006", name: "ข้าวหมูทอดน้ำปลา", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 69, standardCost: 38, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-007", name: "ข้าวไข่ข้นกุ้ง", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 79, standardCost: 45, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-008", name: "ข้าวคั่วกลิ้งหมู", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 69, standardCost: 39, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-009", name: "ข้าวผัดกุนเชียง", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 65, standardCost: 36, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-010", name: "ข้าวหมูผัดพริกแกง", type: "produced_finished_good", category: "ข้าวกล่อง", unit: "จาน", salePrice: 65, standardCost: 35, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-011", name: "น้ำดื่ม 600 มล.", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 10, standardCost: 5, costStartDate: "2026-06-01", supplier: "Grand House", active: false },
  { id: "PGH-012", name: "น้ำดื่ม 600 มล.", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 12, standardCost: 6, costStartDate: "2026-06-20", supplier: "Grand House", active: true },
  { id: "PGH-013", name: "ชาไทย Grand House", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 35, standardCost: 17, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-014", name: "กาแฟดำเย็น", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 35, standardCost: 15, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-015", name: "ลาเต้เย็น", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 45, standardCost: 22, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-016", name: "โกโก้เย็น", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 45, standardCost: 23, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-017", name: "น้ำผึ้งมะนาว", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 40, standardCost: 19, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-018", name: "ชามะนาว", type: "produced_finished_good", category: "น้ำ", unit: "จาน", salePrice: 35, standardCost: 16, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-019", name: "เค้กกล้วยหอม", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 39, standardCost: 18, costStartDate: "2026-06-01", supplier: "Grand House", active: false },
  { id: "PGH-020", name: "เค้กกล้วยหอม", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 45, standardCost: 22, costStartDate: "2026-06-18", supplier: "Grand House", active: true },
  { id: "PGH-021", name: "บราวนี่หน้าแน่น", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 49, standardCost: 25, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-022", name: "คุกกี้ช็อกโกแลต", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 35, standardCost: 16, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-023", name: "แพนเค้กน้ำผึ้ง", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 59, standardCost: 29, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-024", name: "วาฟเฟิล", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 55, standardCost: 27, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-025", name: "ขนมปังปิ้งเนยนม", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 35, standardCost: 14, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-026", name: "ขนมปังปิ้งสังขยา", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 39, standardCost: 16, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-027", name: "ครัวซองต์เนยสด", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 69, standardCost: 38, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-028", name: "ทาร์ตไข่", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 45, standardCost: 24, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-029", name: "มัฟฟินบลูเบอร์รี", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 49, standardCost: 26, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PGH-030", name: "โดนัทน้ำตาล", type: "produced_finished_good", category: "ขนม", unit: "จาน", salePrice: 35, standardCost: 18, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-001", name: "เนื้อไก่สด", type: "raw_material", category: "เนื้อสัตว์", unit: "กก.", salePrice: 0, standardCost: 65, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-002", name: "เนื้อหมูสด", type: "raw_material", category: "เนื้อสัตว์", unit: "กก.", salePrice: 0, standardCost: 85, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-003", name: "กุ้งแชบ๊วย", type: "raw_material", category: "เนื้อสัตว์", unit: "กก.", salePrice: 0, standardCost: 220, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-004", name: "ข้าวหอมมะลิ", type: "raw_material", category: "ของแห้ง", unit: "กก.", salePrice: 0, standardCost: 35, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-005", name: "น้ำมันพืช", type: "raw_material", category: "เครื่องปรุง", unit: "ลิตร", salePrice: 0, standardCost: 45, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-006", name: "ซีอิ๊วขาว", type: "raw_material", category: "เครื่องปรุง", unit: "ลิตร", salePrice: 0, standardCost: 55, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-007", name: "น้ำตาลทราย", type: "raw_material", category: "เครื่องปรุง", unit: "กก.", salePrice: 0, standardCost: 28, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-008", name: "ไข่ไก่เบอร์ 2", type: "raw_material", category: "อื่นๆ", unit: "ฟอง", salePrice: 0, standardCost: 4.5, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-009", name: "ใบกะเพรา", type: "raw_material", category: "ผัก", unit: "กก.", salePrice: 0, standardCost: 80, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-010", name: "พริกขี้หนู", type: "raw_material", category: "ผัก", unit: "กก.", salePrice: 0, standardCost: 60, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-011", name: "กระเทียม", type: "raw_material", category: "เครื่องปรุง", unit: "กก.", salePrice: 0, standardCost: 45, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-012", name: "แป้งสาลี", type: "raw_material", category: "ของแห้ง", unit: "กก.", salePrice: 0, standardCost: 32, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-013", name: "เนยสด", type: "raw_material", category: "อื่นๆ", unit: "กก.", salePrice: 0, standardCost: 180, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-014", name: "นมสด", type: "raw_material", category: "อื่นๆ", unit: "ลิตร", salePrice: 0, standardCost: 55, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-015", name: "ผงโกโก้", type: "raw_material", category: "เครื่องปรุง", unit: "กก.", salePrice: 0, standardCost: 250, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-016", name: "น้ำเปล่า (สำหรับผลิต)", type: "raw_material", category: "น้ำ", unit: "ลิตร", salePrice: 0, standardCost: 5, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "RM-017", name: "น้ำแข็ง", type: "raw_material", category: "น้ำ", unit: "กก.", salePrice: 0, standardCost: 8, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-001", name: "กล่องข้าวกล่อง 600 มล.", type: "packaging", category: "บรรจุภัณฑ์", unit: "ใบ", salePrice: 0, standardCost: 4, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-002", name: "ถุงพลาสติกใส", type: "packaging", category: "บรรจุภัณฑ์", unit: "ใบ", salePrice: 0, standardCost: 1.5, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-003", name: "ช้อนไม้", type: "packaging", category: "บรรจุภัณฑ์", unit: "คัน", salePrice: 0, standardCost: 0.8, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-004", name: "ส้อมไม้", type: "packaging", category: "บรรจุภัณฑ์", unit: "คัน", salePrice: 0, standardCost: 0.8, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-005", name: "ฝาแก้ว 95 มม.", type: "packaging", category: "บรรจุภัณฑ์", unit: "อัน", salePrice: 0, standardCost: 2, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-006", name: "หลอดกระดาษ", type: "packaging", category: "บรรจุภัณฑ์", unit: "อัน", salePrice: 0, standardCost: 1.2, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-007", name: "กล่องเบเกอรี่เล็ก", type: "packaging", category: "บรรจุภัณฑ์", unit: "ใบ", salePrice: 0, standardCost: 3.5, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
  { id: "PK-008", name: "ถุงกระดาษมีหู", type: "packaging", category: "บรรจุภัณฑ์", unit: "ใบ", salePrice: 0, standardCost: 3, costStartDate: "2026-06-01", supplier: "Grand House", active: true },
];

const sampleLots: AppState["lots"] = [
  { id: "LOT-001", productId: "PTG-002", branch: "บ้านโจ้", quantityIn: 40, remaining: 26, unitCost: 35, receivedDate: "2026-06-01", expiryDate: "2026-06-04", source: "ซื้อเข้า", supplier: "The Grand's", note: "เบิกข้าวกะเพราไก่ล็อตเช้า" },
  { id: "LOT-002", productId: "PTG-004", branch: "บ้านโจ้", quantityIn: 35, remaining: 19, unitCost: 34, receivedDate: "2026-06-01", expiryDate: "2026-06-04", source: "ซื้อเข้า", supplier: "The Grand's", note: "เบิกข้าวผัดหมู" },
  { id: "LOT-003", productId: "PTG-012", branch: "บ้านโจ้", quantityIn: 72, remaining: 54, unitCost: 7, receivedDate: "2026-06-01", expiryDate: "2026-06-20", source: "ซื้อเข้า", supplier: "The Grand's", note: "น้ำดื่มเข้าสต็อก" },
  { id: "LOT-004", productId: "PTG-020", branch: "ท่ารั้ว", quantityIn: 24, remaining: 11, unitCost: 23, receivedDate: "2026-06-02", expiryDate: "2026-06-05", source: "ซื้อเข้า", supplier: "The Grand's", note: "เค้กกล้วยหอม" },
  { id: "LOT-005", productId: "PTG-021", branch: "เกษตรใหม่", quantityIn: 20, remaining: 14, unitCost: 26, receivedDate: "2026-06-02", expiryDate: "2026-06-06", source: "ซื้อเข้า", supplier: "The Grand's", note: "บราวนี่" },
  { id: "LOT-006", productId: "PGH-002", branch: "บ้านโจ้", quantityIn: 30, remaining: 18, unitCost: 31.5, receivedDate: "2026-06-02", expiryDate: "2026-06-04", source: "ผลิตเอง", supplier: "Grand House", note: "ผลิตกะเพราไก่รอบแรก" },
  { id: "LOT-007", productId: "PGH-004", branch: "ท่ารั้ว", quantityIn: 24, remaining: 16, unitCost: 34.2, receivedDate: "2026-06-02", expiryDate: "2026-06-04", source: "ผลิตเอง", supplier: "Grand House", note: "ผลิตข้าวผัดหมู" },
  { id: "LOT-008", productId: "PGH-013", branch: "เกษตรใหม่", quantityIn: 30, remaining: 21, unitCost: 18.4, receivedDate: "2026-06-03", expiryDate: "2026-06-05", source: "ผลิตเอง", supplier: "Grand House", note: "ชาไทย Grand House" },
  { id: "LOT-009", productId: "PGH-020", branch: "บ้านโจ้", quantityIn: 18, remaining: 10, unitCost: 21.8, receivedDate: "2026-06-03", expiryDate: "2026-06-06", source: "ผลิตเอง", supplier: "Grand House", note: "เค้กกล้วยหอมผลิตเอง" },
  { id: "LOT-010", productId: "PGH-025", branch: "ท่ารั้ว", quantityIn: 25, remaining: 23, unitCost: 13.7, receivedDate: "2026-06-03", expiryDate: "2026-06-05", source: "ผลิตเอง", supplier: "Grand House", note: "ขนมปังปิ้งเนยนม" },

  { id: "LOT-011", productId: "RM-001", branch: "บ้านโจ้", quantityIn: 12, remaining: 7.4, unitCost: 72, receivedDate: "2026-05-29", expiryDate: "2026-06-04", source: "ซื้อเข้า", supplier: "ตลาดเมืองใหม่", note: "ไก่สดล็อตเก่า ราคาถูก" },
  { id: "LOT-012", productId: "RM-001", branch: "บ้านโจ้", quantityIn: 10, remaining: 10, unitCost: 88, receivedDate: "2026-06-02", expiryDate: "2026-06-07", source: "ซื้อเข้า", supplier: "ตลาดเมืองใหม่", note: "ไก่สดล็อตใหม่ ราคาแพงขึ้น" },
  { id: "LOT-013", productId: "RM-001", branch: "ท่ารั้ว", quantityIn: 8, remaining: 5.6, unitCost: 82, receivedDate: "2026-06-01", expiryDate: "2026-06-06", source: "ซื้อเข้า", supplier: "ฟาร์มเชียงใหม่", note: "ไก่สดสาขาท่ารั้ว" },
  { id: "LOT-014", productId: "RM-001", branch: "เกษตรใหม่", quantityIn: 7, remaining: 6.2, unitCost: 95, receivedDate: "2026-06-03", expiryDate: "2026-06-08", source: "ซื้อเข้า", supplier: "ฟาร์มเชียงใหม่", note: "ไก่สดราคาเร่งด่วน" },
  { id: "LOT-015", productId: "RM-002", branch: "บ้านโจ้", quantityIn: 9, remaining: 4.8, unitCost: 93, receivedDate: "2026-05-30", expiryDate: "2026-06-05", source: "ซื้อเข้า", supplier: "ตลาดเมืองใหม่", note: "หมูสดล็อตแรก" },
  { id: "LOT-016", productId: "RM-002", branch: "ท่ารั้ว", quantityIn: 8, remaining: 7.1, unitCost: 105, receivedDate: "2026-06-03", expiryDate: "2026-06-08", source: "ซื้อเข้า", supplier: "ตลาดเมืองใหม่", note: "หมูสดล็อตราคาใหม่" },
  { id: "LOT-017", productId: "RM-004", branch: "บ้านโจ้", quantityIn: 50, remaining: 32, unitCost: 36, receivedDate: "2026-05-25", expiryDate: "2026-08-25", source: "ซื้อเข้า", supplier: "ร้านข้าวสาร", note: "ข้าวหอมมะลิกระสอบแรก" },
  { id: "LOT-018", productId: "RM-004", branch: "บ้านโจ้", quantityIn: 25, remaining: 25, unitCost: 42, receivedDate: "2026-06-03", expiryDate: "2026-09-03", source: "ซื้อเข้า", supplier: "ร้านข้าวสาร", note: "ข้าวหอมมะลิราคาขึ้น" },
  { id: "LOT-019", productId: "RM-004", branch: "เกษตรใหม่", quantityIn: 30, remaining: 24, unitCost: 39, receivedDate: "2026-06-01", expiryDate: "2026-09-01", source: "ซื้อเข้า", supplier: "ร้านข้าวสาร", note: "ข้าวสาขาเกษตรใหม่" },
  { id: "LOT-020", productId: "RM-005", branch: "บ้านโจ้", quantityIn: 18, remaining: 11.5, unitCost: 48, receivedDate: "2026-05-28", expiryDate: "2026-10-01", source: "ซื้อเข้า", supplier: "แม็คโคร", note: "น้ำมันพืชล็อตเก่า" },
  { id: "LOT-021", productId: "RM-005", branch: "ท่ารั้ว", quantityIn: 12, remaining: 9, unitCost: 52, receivedDate: "2026-06-03", expiryDate: "2026-10-03", source: "ซื้อเข้า", supplier: "แม็คโคร", note: "น้ำมันพืชล็อตใหม่" },
  { id: "LOT-022", productId: "RM-008", branch: "บ้านโจ้", quantityIn: 120, remaining: 74, unitCost: 4.2, receivedDate: "2026-05-31", expiryDate: "2026-06-12", source: "ซื้อเข้า", supplier: "ฟาร์มไข่", note: "ไข่ไก่เบอร์ 2" },
  { id: "LOT-023", productId: "RM-008", branch: "เกษตรใหม่", quantityIn: 90, remaining: 86, unitCost: 4.8, receivedDate: "2026-06-03", expiryDate: "2026-06-14", source: "ซื้อเข้า", supplier: "ฟาร์มไข่", note: "ไข่ไก่ราคาขึ้น" },
  { id: "LOT-024", productId: "RM-009", branch: "บ้านโจ้", quantityIn: 3, remaining: 1.1, unitCost: 90, receivedDate: "2026-06-02", expiryDate: "2026-06-05", source: "ซื้อเข้า", supplier: "ตลาดผัก", note: "ใบกะเพราสด" },
  { id: "LOT-025", productId: "RM-010", branch: "บ้านโจ้", quantityIn: 2.5, remaining: 1.4, unitCost: 75, receivedDate: "2026-06-02", expiryDate: "2026-06-06", source: "ซื้อเข้า", supplier: "ตลาดผัก", note: "พริกขี้หนู" },
  { id: "LOT-026", productId: "RM-011", branch: "ท่ารั้ว", quantityIn: 5, remaining: 4, unitCost: 52, receivedDate: "2026-06-01", expiryDate: "2026-07-01", source: "ซื้อเข้า", supplier: "ตลาดผัก", note: "กระเทียม" },
  { id: "LOT-027", productId: "RM-014", branch: "บ้านโจ้", quantityIn: 24, remaining: 16, unitCost: 58, receivedDate: "2026-06-02", expiryDate: "2026-06-09", source: "ซื้อเข้า", supplier: "ร้านนมสด", note: "นมสดล็อตแรก" },
  { id: "LOT-028", productId: "RM-014", branch: "เกษตรใหม่", quantityIn: 18, remaining: 13, unitCost: 62, receivedDate: "2026-06-03", expiryDate: "2026-06-10", source: "ซื้อเข้า", supplier: "ร้านนมสด", note: "นมสดล็อตสอง" },
  { id: "LOT-029", productId: "PK-001", branch: "บ้านโจ้", quantityIn: 300, remaining: 210, unitCost: 4.1, receivedDate: "2026-05-30", expiryDate: "2027-05-30", source: "ซื้อเข้า", supplier: "ร้านบรรจุภัณฑ์", note: "กล่องข้าว 600 มล." },
  { id: "LOT-030", productId: "PK-002", branch: "ท่ารั้ว", quantityIn: 500, remaining: 430, unitCost: 1.4, receivedDate: "2026-06-01", expiryDate: "2027-06-01", source: "ซื้อเข้า", supplier: "ร้านบรรจุภัณฑ์", note: "ถุงพลาสติกใส" },
];

const sampleRecipes: AppState["recipes"] = [
  { id: "REC-001", name: "สูตรกะเพราไก่ Grand House", outputProductId: "PGH-002", outputQty: 10, outputUnit: "จาน", ingredients: [{ productId: "RM-001", quantity: 2.4, unit: "กก." }, { productId: "RM-004", quantity: 3.5, unit: "กก." }, { productId: "RM-009", quantity: 0.35, unit: "กก." }, { productId: "RM-010", quantity: 0.18, unit: "กก." }, { productId: "RM-011", quantity: 0.22, unit: "กก." }, { productId: "PK-001", quantity: 10, unit: "ใบ" }] },
  { id: "REC-002", name: "สูตรข้าวผัดหมู", outputProductId: "PGH-004", outputQty: 10, outputUnit: "จาน", ingredients: [{ productId: "RM-002", quantity: 2.1, unit: "กก." }, { productId: "RM-004", quantity: 3.8, unit: "กก." }, { productId: "RM-008", quantity: 10, unit: "ฟอง" }, { productId: "RM-005", quantity: 0.45, unit: "ลิตร" }, { productId: "PK-001", quantity: 10, unit: "ใบ" }] },
  { id: "REC-003", name: "สูตรไก่กระเทียม", outputProductId: "PGH-005", outputQty: 12, outputUnit: "จาน", ingredients: [{ productId: "RM-001", quantity: 2.8, unit: "กก." }, { productId: "RM-004", quantity: 4.2, unit: "กก." }, { productId: "RM-011", quantity: 0.35, unit: "กก." }, { productId: "RM-006", quantity: 0.25, unit: "ลิตร" }, { productId: "PK-001", quantity: 12, unit: "ใบ" }] },
  { id: "REC-004", name: "สูตรหมูทอดน้ำปลา", outputProductId: "PGH-006", outputQty: 10, outputUnit: "จาน", ingredients: [{ productId: "RM-002", quantity: 2.7, unit: "กก." }, { productId: "RM-004", quantity: 3.5, unit: "กก." }, { productId: "RM-005", quantity: 0.7, unit: "ลิตร" }, { productId: "RM-006", quantity: 0.18, unit: "ลิตร" }, { productId: "PK-001", quantity: 10, unit: "ใบ" }] },
  { id: "REC-005", name: "สูตรชาไทย Grand House", outputProductId: "PGH-013", outputQty: 20, outputUnit: "จาน", ingredients: [{ productId: "RM-014", quantity: 6, unit: "ลิตร" }, { productId: "RM-007", quantity: 1.2, unit: "กก." }, { productId: "RM-016", quantity: 8, unit: "ลิตร" }, { productId: "RM-017", quantity: 8, unit: "กก." }, { productId: "PK-005", quantity: 20, unit: "อัน" }, { productId: "PK-006", quantity: 20, unit: "อัน" }] },
  { id: "REC-006", name: "สูตรโกโก้เย็น", outputProductId: "PGH-016", outputQty: 18, outputUnit: "จาน", ingredients: [{ productId: "RM-015", quantity: 0.8, unit: "กก." }, { productId: "RM-014", quantity: 5, unit: "ลิตร" }, { productId: "RM-007", quantity: 0.9, unit: "กก." }, { productId: "RM-017", quantity: 7, unit: "กก." }, { productId: "PK-005", quantity: 18, unit: "อัน" }] },
  { id: "REC-007", name: "สูตรเค้กกล้วยหอม", outputProductId: "PGH-020", outputQty: 16, outputUnit: "จาน", ingredients: [{ productId: "RM-012", quantity: 1.8, unit: "กก." }, { productId: "RM-013", quantity: 0.7, unit: "กก." }, { productId: "RM-008", quantity: 16, unit: "ฟอง" }, { productId: "RM-007", quantity: 0.8, unit: "กก." }, { productId: "PK-007", quantity: 16, unit: "ใบ" }] },
  { id: "REC-008", name: "สูตรขนมปังปิ้งเนยนม", outputProductId: "PGH-025", outputQty: 20, outputUnit: "จาน", ingredients: [{ productId: "RM-012", quantity: 1.5, unit: "กก." }, { productId: "RM-013", quantity: 0.5, unit: "กก." }, { productId: "RM-014", quantity: 2.5, unit: "ลิตร" }, { productId: "RM-007", quantity: 0.55, unit: "กก." }, { productId: "PK-007", quantity: 20, unit: "ใบ" }] },
];

const sampleCashEntries: AppState["cashEntries"] = [
  { id: "CASH-001", date: "2026-05-29", branch: "บ้านโจ้", type: "จ่ายเงิน", category: "ค่าวัตถุดิบ", purchaseQty: 12, paymentChannel: "QR1", expenseProductId: "RM-001", amount: 864, note: "ซื้อไก่สดล็อตเก่า ราคาถูก", linkedId: "LOT-011" },
  { id: "CASH-002", date: "2026-06-02", branch: "บ้านโจ้", type: "จ่ายเงิน", category: "ค่าวัตถุดิบ", purchaseQty: 10, paymentChannel: "QR2", expenseProductId: "RM-001", amount: 880, note: "ซื้อไก่สดซ้ำ ราคาสูงขึ้น", linkedId: "LOT-012" },
  { id: "CASH-003", date: "2026-06-03", branch: "เกษตรใหม่", type: "จ่ายเงิน", category: "ค่าวัตถุดิบ", purchaseQty: 7, paymentChannel: "เงินสด", expenseProductId: "RM-001", amount: 665, note: "ซื้อไก่สดเร่งด่วน", linkedId: "LOT-014" },
  { id: "CASH-004", date: "2026-05-30", branch: "บ้านโจ้", type: "จ่ายเงิน", category: "ค่าวัตถุดิบ", purchaseQty: 9, paymentChannel: "QR1", expenseProductId: "RM-002", amount: 837, note: "ซื้อหมูสดล็อตแรก", linkedId: "LOT-015" },
  { id: "CASH-005", date: "2026-06-03", branch: "ท่ารั้ว", type: "จ่ายเงิน", category: "ค่าวัตถุดิบ", purchaseQty: 8, paymentChannel: "QR2", expenseProductId: "RM-002", amount: 840, note: "ซื้อหมูสดล็อตราคาใหม่", linkedId: "LOT-016" },
  { id: "CASH-006", date: "2026-05-25", branch: "บ้านโจ้", type: "จ่ายเงิน", category: "ค่าวัตถุดิบ", purchaseQty: 50, paymentChannel: "QR1", expenseProductId: "RM-004", amount: 1800, note: "ข้าวหอมมะลิกระสอบแรก", linkedId: "LOT-017" },
  { id: "CASH-007", date: "2026-06-03", branch: "บ้านโจ้", type: "จ่ายเงิน", category: "ค่าวัตถุดิบ", purchaseQty: 25, paymentChannel: "QR1", expenseProductId: "RM-004", amount: 1050, note: "ข้าวหอมมะลิราคาขึ้น", linkedId: "LOT-018" },
  { id: "CASH-008", date: "2026-06-02", branch: "บ้านโจ้", type: "จ่ายเงิน", category: "ค่าวัตถุดิบ", purchaseQty: 24, paymentChannel: "เงินสด", expenseProductId: "RM-014", amount: 1392, note: "นมสดล็อตแรก", linkedId: "LOT-027" },
  { id: "CASH-009", date: "2026-06-03", branch: "เกษตรใหม่", type: "จ่ายเงิน", category: "ค่าวัตถุดิบ", purchaseQty: 18, paymentChannel: "QR2", expenseProductId: "RM-014", amount: 1116, note: "นมสดล็อตสอง", linkedId: "LOT-028" },
  { id: "CASH-010", date: "2026-05-30", branch: "บ้านโจ้", type: "จ่ายเงิน", category: "ค่าบรรจุภัณฑ์", purchaseQty: 300, paymentChannel: "QR1", expenseProductId: "PK-001", amount: 1230, note: "กล่องข้าว 600 มล.", linkedId: "LOT-029" },
  { id: "CASH-011", date: "2026-06-01", branch: "ท่ารั้ว", type: "จ่ายเงิน", category: "ค่าบรรจุภัณฑ์", purchaseQty: 500, paymentChannel: "QR2", expenseProductId: "PK-002", amount: 700, note: "ถุงพลาสติกใส", linkedId: "LOT-030" },
  { id: "CASH-012", date: "2026-06-01", branch: "บ้านโจ้", type: "จ่ายเงิน", category: "ค่าแรง", purchaseQty: 1, paymentChannel: "เงินสด", amount: 2400, note: "ค่าแรงพนักงานครัว 1 วัน" },
  { id: "CASH-013", date: "2026-06-02", branch: "ท่ารั้ว", type: "จ่ายเงิน", category: "ค่าสาธารณูปโภค", purchaseQty: 1, paymentChannel: "QR1", amount: 1180, note: "ค่าน้ำค่าไฟสาขาท่ารั้ว" },
  { id: "CASH-014", date: "2026-06-03", branch: "เกษตรใหม่", type: "จ่ายเงิน", category: "ค่าดำเนินงาน", purchaseQty: 1, paymentChannel: "เงินสด", amount: 650, note: "ค่าขนส่งวัตถุดิบ" },
  { id: "CASH-015", date: "2026-06-02", branch: "บ้านโจ้", type: "ย้ายต้นทุน", category: "ผลิตอาหาร", amount: 945, note: "ผลิตสูตรกะเพราไก่ Grand House เป็น LOT-006", linkedId: "BATCH-001" },
  { id: "CASH-016", date: "2026-06-02", branch: "ท่ารั้ว", type: "ย้ายต้นทุน", category: "ผลิตอาหาร", amount: 820.8, note: "ผลิตสูตรข้าวผัดหมูเป็น LOT-007", linkedId: "BATCH-002" },
  { id: "CASH-017", date: "2026-06-03", branch: "เกษตรใหม่", type: "ย้ายต้นทุน", category: "ผลิตอาหาร", amount: 552, note: "ผลิตชาไทย Grand House เป็น LOT-008", linkedId: "BATCH-003" },
  { id: "CASH-018", date: "2026-06-03", branch: "บ้านโจ้", type: "ย้ายต้นทุน", category: "ผลิตอาหาร", amount: 392.4, note: "ผลิตเค้กกล้วยหอมเป็น LOT-009", linkedId: "BATCH-004" },
  { id: "CASH-019", date: "2026-06-03", branch: "ท่ารั้ว", type: "ย้ายต้นทุน", category: "ผลิตอาหาร", amount: 342.5, note: "ผลิตขนมปังปิ้งเนยนมเป็น LOT-010", linkedId: "BATCH-005" },
];

const sampleBatches: AppState["batches"] = [
  { id: "BATCH-001", recipeId: "REC-001", branch: "บ้านโจ้", producedQty: 30, productionDate: "2026-06-02", expiryDate: "2026-06-04", totalCost: 945, outputLotId: "LOT-006" },
  { id: "BATCH-002", recipeId: "REC-002", branch: "ท่ารั้ว", producedQty: 24, productionDate: "2026-06-02", expiryDate: "2026-06-04", totalCost: 820.8, outputLotId: "LOT-007" },
  { id: "BATCH-003", recipeId: "REC-005", branch: "เกษตรใหม่", producedQty: 30, productionDate: "2026-06-03", expiryDate: "2026-06-05", totalCost: 552, outputLotId: "LOT-008" },
  { id: "BATCH-004", recipeId: "REC-007", branch: "บ้านโจ้", producedQty: 18, productionDate: "2026-06-03", expiryDate: "2026-06-06", totalCost: 392.4, outputLotId: "LOT-009" },
  { id: "BATCH-005", recipeId: "REC-008", branch: "ท่ารั้ว", producedQty: 25, productionDate: "2026-06-03", expiryDate: "2026-06-05", totalCost: 342.5, outputLotId: "LOT-010" },
];

const sampleMovements: AppState["movements"] = [
  { id: "MOVE-001", date: "2026-06-02", branch: "บ้านโจ้", lotId: "LOT-006", productId: "PGH-002", type: "ผลิต", quantityChange: 30, valueChange: 945, linkedId: "BATCH-001", note: "ผลิตกะเพราไก่ Grand House" },
  { id: "MOVE-002", date: "2026-06-02", branch: "ท่ารั้ว", lotId: "LOT-007", productId: "PGH-004", type: "ผลิต", quantityChange: 24, valueChange: 820.8, linkedId: "BATCH-002", note: "ผลิตข้าวผัดหมู" },
  { id: "MOVE-003", date: "2026-06-03", branch: "เกษตรใหม่", lotId: "LOT-008", productId: "PGH-013", type: "ผลิต", quantityChange: 30, valueChange: 552, linkedId: "BATCH-003", note: "ผลิตชาไทย Grand House" },
  { id: "MOVE-004", date: "2026-06-03", branch: "บ้านโจ้", lotId: "LOT-009", productId: "PGH-020", type: "ผลิต", quantityChange: 18, valueChange: 392.4, linkedId: "BATCH-004", note: "ผลิตเค้กกล้วยหอม" },
  { id: "MOVE-005", date: "2026-06-03", branch: "ท่ารั้ว", lotId: "LOT-010", productId: "PGH-025", type: "ผลิต", quantityChange: 25, valueChange: 342.5, linkedId: "BATCH-005", note: "ผลิตขนมปังปิ้งเนยนม" },
];

export const initialState: AppState = {
  products,
  lots: sampleLots,
  recipes: sampleRecipes,
  batches: sampleBatches,
  sessions: [],
  sales: [],
  saleItems: [],
  payments: [],
  movements: sampleMovements,
  documents: [],
  cashEntries: sampleCashEntries,
  adjustments: [],
  closeShifts: [],
  auditLogs: [],
  taxSettings: {
    vatEnabled: false,
    vatRate: 7,
    priceIncludesVat: true,
  },
};
